apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebill-estimator-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebill-estimator
  template:
    metadata:
      labels:
        app: ebill-estimator
    spec:
      containers:
      - name: ebill-estimator
        image: lavanya0421/ebill-estimator:latest  # Your image name
        ports:
        - containerPort: 8082  # Your port
---
apiVersion: v1
kind: Service
metadata:
  name: ebill-estimator-service
  namespace: monitoring
spec:
  selector:
    app: ebill-estimator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082  # Your port
  type: NodePort
