apiVersion: v1
kind: Service
metadata:
  name: ebill-estimator-service
spec:
  selector:
    app: ebill-estimator  # This should match the pod's label
  ports:
    - protocol: TCP
      port: 8082            # The port the service will be exposed on
      targetPort: 8082      # The port your app is running on inside the container
  type: ClusterIP          # Service is accessible within the cluster
