apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ebill-estimator-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus  # Matches Prometheus release
spec:
  selector:
    matchLabels:
      app: ebill-estimator-service  # Should match your Service's selector
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
